### ISSUE TITLE
filepath keeps storred in path variable

### ISSUE THREAD

**Issue by LucK1Y** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#49]
Zuerst ich bin mir unsicher, ob es bei dir @Tatenshi  noch so ist. Kann auch sein, dass es nur noch bei meiner alten Version so ist (habs nicht neu gebaut)
- Beim Validieren einer Datei wird ja der Pfad in der Variablen path gespeichert
- Dann wird Validiert
- und dann ist der Pfad immer noch in der Variablen
- beim erneuten Validieren kann keine andere Datei ausgewählt werden

**Comment by Tatenshi** [comment]
Bei der Console Application wird das dokument in ein caex objekt geladen. Das wird dann übergeben an die validate funktion. Das laden passiert jedes mal von neuen. Von daher sollte es kein Problem sein. Kanns aber später nochmal ausprobieren

**Comment by LucK1Y** [comment]
Perfekt 👍
