### ISSUE TITLE
STP Verbesserung

### ISSUE THREAD

**Issue by LucK1Y** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#59]
- STP in Git laden
- STP in 7. Test equipment anpassen, auch sowas wie Computer gehöhrt rein

**Comment by Tatenshi** [comment]
Console Application braucht .NET Framework (in 7.1 ergänzen)

**Comment by Kretsche93** [comment]
"Im STP steht unter 11.3.1 bei step 7, dass der tester das ganze noch unter windows 7 testen soll
im STR haben wir das entfernt gehabt, weil das nicht getestet wurde. das sollte im STP auch noch angepasst werden
bei der gelegenheit sollte die formulierung von 11.3.2 vom stp bei step 1 im wiki auch angepasst werden"

**Comment by Kretsche93** [comment]
Issues fixed and pushed
