### ISSUE TITLE
Create Document SAS

### ISSUE THREAD

**Issue by Tatenshi** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#6]

**Comment by Tatenshi** [comment]
Created

**Comment by GotLucKy** [comment]
[TINF18C_SAS_Team_4_1v0.pdf](https://github.com/RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface/files/3815281/TINF18C_SAS_Team_4_1v0.pdf)
