### ISSUE TITLE
Consolen Application improvements

### ISSUE THREAD

**Issue by LucK1Y** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#60]
- in options spelling mistake
- check flags ( "-h", "--help") and others
- improve work flow 
````bash
if aml file given -> always validate -> options to compress
if amlx file given-> (always ?) decompress -> validate ??
````

**Comment by Tatenshi** [comment]
Spelling Mistake und Help behoben

**Comment by Tatenshi** [comment]
ToDo: Header ergänzen

**Comment by Tatenshi** [comment]
line number of errors in AML files when validating

**Comment by Tatenshi** [comment]
Add Version number in header

**Comment by Tatenshi** [comment]
Insert console application name in the title page in the command line application UI.

**Comment by wodyy666** [comment]
TC-003-001 UI-Test:
	1. ok
	2. quick selection of options using -v V 1 or something similar
	3. allow numbers not only name of configuration (QOL)
	   change of configuration value --> next screen has no CLS and instead prints underneath existing window - intended behaviour?
	   Redirecting to main menu?!?
	   show current value before selecting the option
	   save options after restart
	4. yes/no during validate only accepts full "yes" no y or default
       selection of multiple files
    5. nothing new to add
	6. nothing new to add
	7. n/a
	no wait to quit, message stays anyway
	remove unecessarily long footer
	dumps me in main menu even after using cli
	
TC-003-002 Validation-Test:
	no check whether a file with the same name already exists in the selected directory

TC-003-003 (De-)Compression Test:
	see compresssamefiletwice.jpg
	
TC-003-004 Import Test:
	it says you can choose a folder to compress bit you can't

**Comment by Tatenshi** [comment]
Donate entfernen

**Comment by Tatenshi** [comment]
CommandlineClass private machen
