### ISSUE TITLE
Change C++ Wrapper documentation

### ISSUE THREAD

**Issue by Kretsche93** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#64]
Preparation (https://github.com/RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface/blob/MOD_010_C++Wrapper/SOURCE/MOD_010_C++Wrapper/docs/c++%20wrapper/1_preparation.md)
- Change second screenshot so it shows the correct details of the installation ("Desktopentwicklung mit C++" instead of "Einzelne Komponenten")
- In 2_download_aml_engine.md Step 4: After clicking “Add reference...” No “Browse” clickable
- rest of test steps not yet doable

**Comment by LucK1Y** [comment]
Add seconc explanational screenshot for browse button in Chapter https://github.com/RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface/blob/MOD_010_C%2B%2BWrapper/SOURCE/MOD_010_C%2B%2BWrapper/docs/c%2B%2B%20wrapper/2_download_aml_engine.md#4-adding-a-reference

**Comment by LucK1Y** [comment]
``rest of test steps not yet doable`` - now they are
Good Luck

~ still working on the screenshot  for ``correct details of the installation``

**Comment by LucK1Y** [comment]
https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2019 

Link einbauen

**Comment by LucK1Y** [comment]
maybe installing also "Universal Windows Platform development"

**Comment by LucK1Y** [comment]
Cahange order, clr has to be done first

**Comment by LucK1Y** [comment]
#74 should work
