### ISSUE TITLE
Write Modul Documentation (Console Application)

### ISSUE THREAD

**Issue by Tatenshi** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#66]
@ChrisThor die ersten 3 Punkte
@Tatenshi die restlichen

**Comment by Tatenshi** [comment]
Meine Punkte sind fertig.
@ChrisThor bitte Issue schließen wenn du fertig bist.

**Comment by Tatenshi** [comment]
@Tatenshi Erstes Modul fertig machen
@Kretsche93 Zweites Modul fertig machen
@ChrisThor Drittes Modul fertig machen

**Comment by Kretsche93** [comment]
Also mein Teil ist fertig.

**Comment by Tatenshi** [comment]
Meiner auch
