### ISSUE TITLE
Write Modul Documentation (C++ Wrapper)

### ISSUE THREAD

**Issue by Tatenshi** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#67]

**Comment by LucK1Y** [comment]
https://github.com/RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface/wiki/Module%20Documentation%20C++%20Wrapper

**Comment by LucK1Y** [comment]
Ändern & Anpassen
Vorlage JS-module nehmen

**Comment by LucK1Y** [comment]
Reihenfolge ändern, clr direkt am Anfang einstellen
