### ISSUE TITLE
Update Module Docu

### ISSUE THREAD

**Issue by Kretsche93** [RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface#71]
#70

**Comment by LucK1Y** [comment]
Vorlage: https://github.com/RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface/wiki/MOD.021-:-Node-Package-Documentation

**Comment by Kretsche93** [comment]
JS Wrapper part is done
